language: node_js
sudo: false
node_js:
  - 5
  - 6
  - 7
  - 8
# NodeJS v4 requires gcc 4.8

# safelist
branches:
  only:
  - master
  - develop
env:
  - NODE_ENV=development
matrix:
  allow_failures:
    - node_js: 5
services:
  - mongodb
before_install:
  - gem update --system
  - gem install sass --version "=3.5.1"
  - npm i nsp -g
  - npm install protractor
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'node_modules/protractor/bin/webdriver-manager update --standalone --firefox'
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - sleep 3
after_script:
  - nsp audit-package
  - grunt coverage
notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
